/**
 * 串行执行
 */
let async = require('async');
console.time('cost');
async.series([
  function(cb){
    setTimeout(function(){
      console.log(1);
      //异步代码完成后要调用cb,并传入错误对象和返回值
      cb(null,'1');
    },2000)
  },
  function(cb){
    setTimeout(function(){
      console.log(2);
      cb('我错了','2');
    },3000)
  },
  function(cb){
    setTimeout(function(){
      console.log(3);
      cb(null,'3');
    },1000)
  }
],function(err,result){
  console.log(err);
  console.log(result);
  console.timeEnd('cost');
});
